driver:
  name: openstack
platforms:
  - name: test-network_bridge-ubuntu
    image: Ubuntu18.04
provisioner:
  inventory:
    group_vars:
      all:
        network_bridge_devices:
          br0:
            dns:
              - 8.8.8.8
              - 8.8.4.4
            device: ens3
        molecule_openstack_ci_ssh_user: ubuntu
