galaxy_info:
  author: oasis_roles
  description: A role that ensures the chronyd service is installed and running
  company: Red Hat, Inc.
  license: GPLv3
  min_ansible_version: 2.4
  platforms:
    - name: EL
      versions:
        - 7

  galaxy_tags:
    - oasis

dependencies: []
