- name: preconfigure users
  hosts: all
  become: true
  roles:
    - role: users_and_groups
      users_and_groups_add_modify_groups:
        - name: derp
      users_and_groups_add_modify_users:
        - name: derp
          home: /home/derp
          group: derp
          shell: /bin/bash
      users_and_groups_add_group_members:
        - name: derp
          primary_group: derp
          groups:
            - derp
            - wheel
  tasks:
    - name: enable ssh, because that's how this all works
      service:
        name: sshd
        state: started
        enabled: true

    - name: install tools needed
      package:
        name: openssh-clients
        state: present

    - name: create ansible remote dir
      file:
        path: /tmp/ansible
        mode: "0777"
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
