- hosts: all
  roles:
    - role: oasis_roles.rhsm
      rhsm_username: "{{ lookup('env', 'OASIS_RHSM_USERNAME') }}"
      rhsm_password: "{{ lookup('env', 'OASIS_RHSM_PASSWORD') }}"
      rhsm_server_hostname: "{{ lookup('env', 'OASIS_RHSM_SERVER_HOSTNAME') }}"
      rhsm_pool_ids: "{{ lookup('env', 'OASIS_RHSM_POOL_IDS') }}"
      rhsm_repositories:
        enabled:
          - rhel-7-server-rpms
          - rhel-7-server-extras-rpms
          - rhel-7-server-optional-rpms
