- block:
    - name: create sysctl bridge config
      template:
        src: sysctl_bridge.conf
        dest: /etc/sysctl.d/bridge.conf
        owner: root
        mode: "0644"

    - name: create udev rules file
      template:
        src: 99-bridge.rules
        dest: /etc/udev/rules.d/99-bridge.rules
        owner: root
        mode: "0644"

    - name: set bridge in bridged connection
      lineinfile:
        path: "{{ network_bridge_folder }}/ifcfg-{{ bridge.value.device }}"
        line: BRIDGE={{ bridge.key }}
        regexp: "^BRIDGE=.*$"
      notify: restart networking

    - name: create bridge connection
      template:
        src: ifcfg-bridge
        dest: "{{ network_bridge_folder }}/ifcfg-{{ bridge.key }}"
        owner: root
        mode: "0644"
      notify: restart networking
  become: "{{ network_bridge_become }}"
  become_user: "{{ network_bridge_become_user }}"
