galaxy_info:
  author: oasis_roles
  description: Role to install cockpit to a set of hosts and start the service
  company: Red Hat, Inc.
  license: GPLv3
  min_ansible_version: 2.4
  platforms:
    - name: EL
      versions:
        - 7

  galaxy_tags:
    - oasis
