galaxy_info:
  author: oasis_roles
  description: Uploads files (not templates) to the remote host
  company: Red Hat, Inc.
  license: GPLv3
  min_ansible_version: 2.4
  platforms:
    - name: EL
      versions:
        - all
    - name: Linux
      versions:
        - all

  galaxy_tags:
    - oasis

dependencies: []
