galaxy_info:
  author: oasis_roles
  description: Remove disk signatures and erase data from a list of disks
  company: Red Hat, Inc.
  license: GPLv3
  min_ansible_version: 2.4
  platforms:
    - name: EL
      versions:
        - 7

  galaxy_tags:
    - oasis

dependencies: []
