dependency:
  name: galaxy
driver:
  name: openstack
lint:
  name: yamllint
  options:
    config-file: tests/yamllint.yml
platforms:
  - name: test-docker
    image: Fedora 29
    flavor: m1.medium
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    prepare: ../shared/prepare.yml
    converge: ../shared/playbook.yml
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
  directory: ../shared/
