- name: upload setup-domain.sh
  template:
    src: setup_domain.sh
    dest: /tmp/setup_domain.sh
    owner: root
    group: root
    mode: "0755"

- name: run domain install script
  command: /tmp/setup_domain.sh
  register: _libvirt_shell_output
  changed_when: _libvirt_shell_output.rc == 2
  failed_when: _libvirt_shell_output.rc == 1
