driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: container-el7
    box: generic/oracle7
    memory: 2048
    config_options:
      synced_folder: false
      cachier: false
    provider_raw_config_args:
      - 'qemu_use_session = true'
      - 'driver = "qemu"'
provisioner:
  playbooks:
    prepare: ../shared/prepare.yml
    converge: ../shared/playbook.yml
