driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: container-default
    box: generic/fedora34
provisioner:
  playbooks:
    prepare: ../shared/prepare.yml
    converge: ../shared/playbook.yml
