- name: converge
  hosts: all
  roles:
    - role: nfs_server
      vars:
        nfs_server_shares:
          - share_path: /srv/share1
            host_allow: '*'
            opts: rw,sync,all_squash
            create_dir: true
            owner: nfsnobody
            group: nfsnobody
            mode: '0755'
