galaxy_info:
  author: oasis_roles
  description: >-
    Installs and configures iptables rules on a box
  company: Red Hat, Inc.
  license: GPLv3
  min_ansible_version: 2.8
  platforms:
    - name: EL
      versions:
        - 8

  galaxy_tags:
    - oasis

dependencies: []
