driver:
  name: docker
platforms:
  - name: passwordless_ssh_docker
    image: centos/systemd
    privileged: true
    command: /usr/lib/systemd/systemd --system
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
