- name: Set platform/version specific variables
  include_vars: "{{ __rolename_vars_file }}"
  loop:
    - default.yml
    - "{{ ansible_facts.os_family }}.yml"
    - "{{ ansible_facts.distribution }}.yml"
    - "{{ ansible_facts.distribution }}_{{ ansible_facts.distribution_major_version }}.yml"
    - "{{ ansible_facts.distribution }}_{{ ansible_facts.distribution_version }}.yml"
  vars:
    __rolename_vars_file: "{{ role_path }}/vars/{{ item }}"
  when: __rolename_vars_file is file

- name: install packages, if needed
  become: "{{ timezone_become }}"
  become_user: "{{ timezone_become_user }}"
  package:
    name: "{{ timezone_packages }}"
    state: present

- name: set timezone info
  timezone:
    name: "{{ timezone | default(omit, true) }}"
    hwclock: "{{ timezone_hwclock | default(omit, true) }}"
