galaxy_info:
  author: oasis_roles
  description: |-
    Creates a network bridge and attaches specified devices to it
  company: Red Hat, Inc.
  license: GPLv3
  min_ansible_version: 2.8
  platforms:
    - name: EL
      versions:
        - 7

  galaxy_tags:
    - oasis

dependencies: []
