galaxy_info:
  author: oasis_roles
  description: Install NFS server and configure shares
  company: Red Hat, Inc.
  license: GPLv3
  min_ansible_version: 2.4
  platforms:
    - name: EL
      versions:
        - 7
        - 8

  galaxy_tags:
    - oasis

dependencies: []
