- become: "{{ upload_files_become }}"
  block:
    - name: check for destination
      stat:
        path: "{{ item.dest | dirname }}"
      register: __upload_files_stat
      loop: "{{ upload_files }}"

    - name: create target directories, where not exist
      file:
        path: "{{ item.item.dest | dirname }}"
        mode: "{{ item.item.mode | default('0755') }}"
        owner: "{{ item.item.owner | default(omit) }}"
        group: "{{ item.item.group | default(omit) }}"
        selevel: "{{ item.item.selevel | default(omit) }}"
        serole: "{{ item.item.serole | default(omit) }}"
        setype: "{{ item.item.setype | default(omit) }}"
        seuser: "{{ item.item.seuser | default(omit) }}"
        state: directory
      become: "{{ upload_files_become }}"
      loop: "{{ __upload_files_stat.results }}"
      when: not item.stat.exists

    - name: upload files
      copy:
        dest: "{{ item.dest }}"
        attributes: "{{ item.attributes | default(omit) }}"
        backup: "{{ item.backup | default(omit) }}"
        checksum: "{{ item.checksum | default(omit) }}"
        content: "{{ item.content | default(omit) }}"
        decrypt: "{{ item.decrypt | default(omit) }}"
        directory_mode: "{{ item.directory_mode | default(omit) }}"
        follow: "{{ item.follow | default(omit) }}"
        force: "{{ item.force | default(omit) }}"
        group: "{{ item.group | default(omit) }}"
        local_follow: "{{ item.local_follow | default(omit) }}"
        mode: "{{ item.mode | default(omit) }}"
        owner: "{{ item.owner | default(omit) }}"
        remote_src: "{{ item.remote_src | default(omit) }}"
        selevel: "{{ item.selevel | default(omit) }}"
        serole: "{{ item.serole | default(omit) }}"
        setype: "{{ item.setype | default(omit) }}"
        seuser: "{{ item.seuser | default(omit) }}"
        src: "{{ item.src | default(omit) }}"
        unsafe_writes: "{{ item.unsafe_writes | default(omit) }}"
        validate: "{{ item.validate | default(omit) }}"
      become: "{{ upload_files_become }}"
      with_items: "{{ upload_files }}"
